platform :ios, '9.1'
inhibit_all_warnings!

target:'JWNetworking' do

    #pod 'AFNetworking', '3.1.0', :subspecs => ['Reachability', 'Serialization', 'Security', 'NSURLSession']
    pod 'AFNetworking'
    pod 'JWTrace'
end
